import assert from 'node:assert/strict';
import { Workshop } from './karakuri-core.mjs';
const finish = g => { g.start(); for (let i = 0; i < 160; i++) g.step(.05); };
const solve = g => { for (const p of g.parts) { const t = g.targets()[p.id]; g.move(p.id, t.x, t.z); p.angle = 0; } };
const g = new Workshop();
finish(g); assert.equal(g.state, 'failed'); assert.match(g.message, /ハンドル/);
g.reset(); solve(g); const c = g.connections();
assert.deepEqual(c.speeds, { handle: 2, small: -2, large: 1.2, idler: 0, lift: 1.2 });
g.start(); const before = JSON.stringify(g.parts); g.move('small', 5, 3); g.rotate('rail'); assert.equal(JSON.stringify(g.parts), before);
for (let i = 0; i < 160; i++) g.step(.05); assert.equal(g.state, 'success');
g.reset(); assert.equal(g.lift, 0); assert.equal(g.travel, 0); assert.equal(JSON.stringify(g.parts), before);
finish(g); assert.equal(g.state, 'success');
g.reset(); g.rotate('rail'); finish(g); assert.equal(g.state, 'failed'); assert.match(g.message, /レール/);
g.reset(); solve(g); g.rotate('belt'); finish(g); assert.match(g.message, /ベルト/);
g.reset(); solve(g); g.move('large', -1.8, 1, false); finish(g); assert.match(g.message, /噛み合/);
g.reset(); solve(g); g.move('small', -3.6, 0, false); assert.equal(g.connections().input, false);
g.reset(); g.move('small', -3.6, .2); assert.equal(g.parts[0].x, -3.4); assert.equal(g.parts[0].z, 0);
g.init(); assert.equal(g.state, 'edit'); assert.equal(g.parts[0].x, -5);
console.log('Karakuri: success, three failure causes, lock, snap, reset and replay passed.');
