import * as defaultCatalog from './data.mjs';
import { resolveCombat, canFight, combatForecast, sinkCargo } from './combat.mjs';
import { assignCitizens, settleCivilization } from './economy.mjs';
import { createInitialState, validateSnapshot } from './state.mjs';
import { buildCivilizationView, refreshIntelligence, visibleTileIds } from './view.mjs';
import { adjacent, cityRadiusTiles, getTile, terrainPassable } from './world.mjs';
import { chebyshevWrapped, clone, idOf, isAtWar, isRecord, makeId, normalizedPoint, relationFor, scaled, sameTile } from './rules.mjs';

const REASONS = new Set(['INVALID_COMMAND', 'NOT_ACTIVE_CIV', 'NOT_FOUND', 'NOT_OWNER', 'NOT_VISIBLE', 'ILLEGAL_TARGET', 'INSUFFICIENT_MOVEMENT', 'PREREQUISITE_MISSING', 'QUEUE_FULL', 'INVALID_ALLOCATION', 'DIPLOMACY_REQUIRED', 'GAME_OVER']);
const fail = (reason) => ({ ok: false, reason: REASONS.has(reason) ? reason : 'INVALID_COMMAND', events: [] });
const good = (state, rows) => {
  const events = rows.map((row) => ({ id: `event-${state.nextId++}`, type: row.type, round: row.round ?? state.turn.round, civId: row.civId ?? null, entityId: row.entityId ?? null, data: row.data || {} })); state.chronicle.push(...events); return { ok: true, reason: null, events };
};
const adjustRelation = (state, a, b, amount) => { const relation = relationFor(state, a, b); if (relation) relation.value = Math.max(-100, Math.min(100, relation.value + amount)); };
const isCivilian = (catalog, unit) => ['settler', 'worker'].includes(catalog.UNITS[unit.typeId].role);

export class CivilizationEngine {
  constructor() { this.catalog = defaultCatalog; this.state = null; }
  init(config) { const state = createInitialState(config, this.catalog); if (!state) return fail('INVALID_COMMAND'); this.state = state; state.civilizations.forEach((civ) => refreshIntelligence(state, civ.id)); return good(state, [{ type: 'game.started', civId: null, entityId: null, data: { seed: state.config.seed } }]); }
  serialize() { return this.state ? clone(this.state) : null; }
  load(snapshot) { if (!validateSnapshot(snapshot, this.catalog)) return { ok: false, reason: snapshot?.rulesVersion !== this.catalog.RULES_VERSION ? 'INCOMPATIBLE_VERSION' : 'INVALID_SNAPSHOT', events: [] }; this.state = clone(snapshot); return { ok: true, reason: null, events: [] }; }
  getView(civId) { return this.state ? buildCivilizationView(this.state, this.catalog, civId) : null; }
  inspectMove(civId, unitId, to) { if (!this.state || !idOf(this.state.civilizations, civId)) return { cost: null, blocked: true, reason: 'NOT_FOUND', path: [] }; const unit = idOf(this.state.units, unitId); if (!unit || unit.ownerId !== civId || unit.transportedByUnitId) return { cost: null, blocked: true, reason: !unit ? 'NOT_FOUND' : 'NOT_OWNER', path: [] }; const destination = normalizedPoint(this.state.world, to); if (!destination) return { cost: null, blocked: true, reason: 'ILLEGAL_TARGET', path: [] }; if (!visibleTileIds(this.state, civId).has(destination.y * this.state.world.width + destination.x)) return { cost: null, blocked: true, reason: 'NOT_VISIBLE', path: [] }; if (chebyshevWrapped(this.state.world, unit, destination) !== 1) return { cost: null, blocked: true, reason: 'ILLEGAL_TARGET', path: [] }; const tile = getTile(this.state.world, destination.x, destination.y); const enemy = this.state.units.find((candidate) => candidate.transportedByUnitId === null && candidate.x === destination.x && candidate.y === destination.y && candidate.ownerId !== civId && !isCivilian(this.catalog, candidate)); if (!terrainPassable(this.catalog, this.catalog.UNITS[unit.typeId], tile)) return { cost: null, blocked: true, reason: 'ILLEGAL_TARGET', path: [] }; if (enemy && (isCivilian(this.catalog, unit) || !canFight(this.state, unit, enemy))) return { cost: null, blocked: true, reason: isCivilian(this.catalog, unit) ? 'ILLEGAL_TARGET' : 'DIPLOMACY_REQUIRED', path: [] }; const cost = tile.routeId === 'railroad' ? 0.25 : tile.routeId === 'road' ? 0.5 : this.catalog.TERRAIN[tile.terrainId].move; if (unit.movementLeft < Math.min(cost, this.catalog.UNITS[unit.typeId].movement)) return { cost, blocked: true, reason: 'INSUFFICIENT_MOVEMENT', path: [] }; return { cost, blocked: false, reason: null, path: [{ x: destination.x, y: destination.y }], combat: enemy ? combatForecast(this.state, this.catalog, unit, enemy) : null };
  }
  findPath(civId, unitId, to) { if (!this.state) return { cost: null, blocked: true, reason: 'NOT_FOUND', path: [] }; const unit = idOf(this.state.units, unitId); const goal = normalizedPoint(this.state.world, to); if (!unit || !goal) return { cost: null, blocked: true, reason: !unit ? 'NOT_FOUND' : 'ILLEGAL_TARGET', path: [] }; if (unit.ownerId !== civId || unit.transportedByUnitId) return { cost: null, blocked: true, reason: unit.ownerId !== civId ? 'NOT_OWNER' : 'ILLEGAL_TARGET', path: [] }; const intel = this.state.intelligence.find((item) => item.observerCivId === civId); const known = new Set(intel?.exploredTileIds || []); const frontier = [{ x: unit.x, y: unit.y, path: [], cost: 0 }]; const best = new Map([[`${unit.x},${unit.y}`, 0]]); while (frontier.length) { frontier.sort((a, b) => a.cost - b.cost); const current = frontier.shift(); if (sameTile(current, goal)) return { cost: current.cost, blocked: false, reason: null, path: current.path }; for (const tile of adjacent(this.state.world, current)) { const certainty = known.has(tile.id) ? 'known' : 'estimated'; if (certainty === 'known' && !terrainPassable(this.catalog, this.catalog.UNITS[unit.typeId], tile)) continue; const cost = certainty === 'known' ? (tile.routeId === 'railroad' ? 0.25 : tile.routeId === 'road' ? 0.5 : this.catalog.TERRAIN[tile.terrainId].move) : 1; const nextCost = current.cost + cost; const key = `${tile.x},${tile.y}`; if (best.has(key) && best.get(key) <= nextCost) continue; best.set(key, nextCost); frontier.push({ x: tile.x, y: tile.y, path: [...current.path, { x: tile.x, y: tile.y, cost, certainty }], cost: nextCost }); } } return { cost: null, blocked: true, reason: 'ILLEGAL_TARGET', path: [] };
  }
  getPathPreview(civId, unitId, to) { const found = this.findPath(civId, unitId, to); if (found.blocked) return { ok: false, reason: found.reason, path: [], totalCost: null, arrivalRound: null }; const unit = idOf(this.state.units, unitId); let remaining = unit.movementLeft; let round = this.state.turn.round; const path = found.path.map((point) => { if (Math.min(point.cost, this.catalog.UNITS[unit.typeId].movement) > remaining) { round += 1; remaining = this.catalog.UNITS[unit.typeId].movement; } remaining -= Math.min(point.cost, remaining, this.catalog.UNITS[unit.typeId].movement); return { ...point, arrivalRound: round }; }); return { ok: true, reason: null, path, totalCost: found.cost, arrivalRound: path.at(-1)?.arrivalRound ?? this.state.turn.round }; }
  getCombatPreview(civId, attackerUnitId, defenderUnitId) { const attacker = idOf(this.state?.units || [], attackerUnitId); const defender = idOf(this.state?.units || [], defenderUnitId); if (!attacker || !defender) return { ok: false, reason: 'NOT_FOUND', attackerPower: null, defenderPower: null, winChance: null }; if (attacker.ownerId !== civId) return { ok: false, reason: 'NOT_OWNER', attackerPower: null, defenderPower: null, winChance: null }; if (!visibleTileIds(this.state, civId).has(defender.y * this.state.world.width + defender.x)) return { ok: false, reason: 'NOT_VISIBLE', attackerPower: null, defenderPower: null, winChance: null }; if (chebyshevWrapped(this.state.world, attacker, defender) !== 1 || isCivilian(this.catalog, attacker) || isCivilian(this.catalog, defender)) return { ok: false, reason: 'ILLEGAL_TARGET', attackerPower: null, defenderPower: null, winChance: null }; if (!canFight(this.state, attacker, defender)) return { ok: false, reason: 'DIPLOMACY_REQUIRED', attackerPower: null, defenderPower: null, winChance: null }; const forecast = combatForecast(this.state, this.catalog, attacker, defender); return { ok: true, reason: null, attackerPower: forecast.attack, defenderPower: forecast.defense, winChance: forecast.attackerWinChance }; }
  dispatch(command) {
    if (!this.state || !isRecord(command) || typeof command.type !== 'string' || typeof command.civId !== 'string') return fail('INVALID_COMMAND'); if (this.state.turn.status !== 'running') return fail('GAME_OVER'); if (command.civId !== this.state.turn.activeCivId) return fail('NOT_ACTIVE_CIV');
    if (idOf(this.state.civilizations, command.civId)?.eliminated && command.type !== 'civ.endTurn') return fail('NOT_OWNER'); const next = clone(this.state); const rows = []; const outcome = this.#apply(next, command, rows); if (outcome) return fail(outcome); this.#refreshTradeRoutes(next); this.state = next; return good(this.state, rows);
  }
  #owned(state, command, key, collection) { const entity = idOf(state[collection], command[key]); if (!entity) return [null, 'NOT_FOUND']; return entity.ownerId !== command.civId ? [null, 'NOT_OWNER'] : [entity, null]; }
  #advanceUnit(state, unit, destination, cost) { unit.x = destination.x; unit.y = destination.y; state.units.filter((candidate) => candidate.transportedByUnitId === unit.id).forEach((cargo) => { cargo.x = destination.x; cargo.y = destination.y; }); unit.movementLeft = Math.max(0, unit.movementLeft - cost); unit.stance = 'active'; unit.order = null; }
  #hasActiveTreaty(state, a, b, kinds) { return state.treaties.some((treaty) => treaty.status === 'active' && kinds.includes(treaty.kind) && (treaty.civAId === a && treaty.civBId === b || treaty.civAId === b && treaty.civBId === a)); }
  #foreignTerritoryOwner(state, civId, point) { const city = state.cities.find((candidate) => candidate.ownerId !== civId && cityRadiusTiles(state.world, candidate).some((tile) => tile.x === point.x && tile.y === point.y)); return city?.ownerId || null; }
  #captureCity(state, attacker, city, rows) { const defenders = state.units.filter((unit) => unit.x === city.x && unit.y === city.y && unit.ownerId === city.ownerId && !isCivilian(this.catalog, unit)); if (defenders.length) return; const oldOwner = city.ownerId; city.ownerId = attacker.ownerId; city.lockedTileIds = []; city.workedTileIds = []; city.specialists = { scientist: city.population, taxCollector: 0, entertainer: 0 }; city.focus = 'balanced'; if(!idOf(state.civilizations,attacker.ownerId).capitalCityId)idOf(state.civilizations,attacker.ownerId).capitalCityId=city.id; if (idOf(state.civilizations, oldOwner).capitalCityId === city.id) { const replacement = state.cities.find((candidate) => candidate.ownerId === oldOwner); idOf(state.civilizations, oldOwner).capitalCityId = replacement?.id || null; } rows.push({ type: 'city.captured', civId: attacker.ownerId, entityId: city.id, data: { previousOwnerId: oldOwner } }); }
  #move(state, command, rows) { const [unit, ownedReason] = this.#owned(state, command, 'unitId', 'units'); if (ownedReason) return ownedReason; if (unit.transportedByUnitId) return 'ILLEGAL_TARGET'; const destination = normalizedPoint(state.world, command.to); if (!destination || chebyshevWrapped(state.world, unit, destination) !== 1) return 'ILLEGAL_TARGET'; const tile = getTile(state.world, destination.x, destination.y); const destinationVisible = visibleTileIds(state, command.civId).has(tile.id); if (!destinationVisible && !command.fromPath) return 'NOT_VISIBLE'; const hiddenEnemy = command.fromPath && !destinationVisible && state.units.some((candidate) => candidate.transportedByUnitId === null && candidate.x === destination.x && candidate.y === destination.y && candidate.ownerId !== command.civId); if (hiddenEnemy) { state.civilizations.forEach((civ) => refreshIntelligence(state, civ.id)); return 'NOT_VISIBLE'; } if (!terrainPassable(this.catalog, this.catalog.UNITS[unit.typeId], tile)) return 'ILLEGAL_TARGET'; const defender = state.units.find((candidate) => candidate.transportedByUnitId === null && candidate.x === destination.x && candidate.y === destination.y && candidate.ownerId !== command.civId && !isCivilian(this.catalog, candidate)); const civilian = state.units.find((candidate) => candidate.transportedByUnitId === null && candidate.x === destination.x && candidate.y === destination.y && candidate.ownerId !== command.civId && isCivilian(this.catalog, candidate)); if(isCivilian(this.catalog,unit)&&state.cities.some(city=>city.ownerId!==command.civId&&city.x===destination.x&&city.y===destination.y&&isAtWar(state,command.civId,city.ownerId)))return 'ILLEGAL_TARGET'; const territoryOwner = this.#foreignTerritoryOwner(state, command.civId, destination); if (territoryOwner && !isAtWar(state, command.civId, territoryOwner) && !this.#hasActiveTreaty(state, command.civId, territoryOwner, ['openBorders', 'alliance'])) return 'DIPLOMACY_REQUIRED'; if (defender && (isCivilian(this.catalog, unit) || !canFight(state, unit, defender))) return isCivilian(this.catalog, unit) ? 'ILLEGAL_TARGET' : 'DIPLOMACY_REQUIRED'; if (civilian && (isCivilian(this.catalog, unit) || !isAtWar(state, command.civId, civilian.ownerId))) return isCivilian(this.catalog, unit) ? 'ILLEGAL_TARGET' : 'DIPLOMACY_REQUIRED'; const cost = tile.routeId === 'railroad' ? 0.25 : tile.routeId === 'road' ? 0.5 : this.catalog.TERRAIN[tile.terrainId].move; if (unit.movementLeft < Math.min(cost, this.catalog.UNITS[unit.typeId].movement)) return 'INSUFFICIENT_MOVEMENT'; const inspected = { cost, path: [destination] };
    if (defender) { const result = resolveCombat(state, this.catalog, unit, defender); unit.movementLeft = 0; rows.push({ type: 'combat.resolved', civId: command.civId, entityId: unit.id, data: { attackerId: unit.id, defenderId: defender.id, ...result } }); if (result.attackerDestroyed) { if (this.catalog.UNITS[unit.typeId].domain === 'sea') rows.push({ type: 'unit.sank', civId: command.civId, entityId: unit.id, data: { cargoUnitIds: sinkCargo(state, unit.id) } }); return null; } if (!result.defenderDestroyed || state.units.some((candidate) => candidate.transportedByUnitId === null && candidate.x === destination.x && candidate.y === destination.y && candidate.ownerId !== command.civId && !isCivilian(this.catalog, candidate))) return null; if (this.catalog.UNITS[defender.typeId].domain === 'sea') rows.push({ type: 'unit.sank', civId: defender.ownerId, entityId: defender.id, data: { cargoUnitIds: sinkCargo(state, defender.id) } }); }
    this.#advanceUnit(state, unit, destination, inspected.cost); const enemyCivilian = state.units.find((candidate) => candidate.ownerId !== command.civId && candidate.x === destination.x && candidate.y === destination.y && isCivilian(this.catalog, candidate)); if (enemyCivilian && isAtWar(state, command.civId, enemyCivilian.ownerId)) { enemyCivilian.ownerId = command.civId; enemyCivilian.stance = 'waiting'; rows.push({ type: 'unit.captured', civId: command.civId, entityId: enemyCivilian.id, data: {} }); }
    const city = state.cities.find((candidate) => candidate.x === destination.x && candidate.y === destination.y && candidate.ownerId !== command.civId); if (city && isAtWar(state, command.civId, city.ownerId)) this.#captureCity(state, unit, city, rows); state.civilizations.forEach((civ) => refreshIntelligence(state, civ.id)); rows.push({ type: 'unit.moved', civId: command.civId, entityId: unit.id, data: { to: destination, cost: inspected.cost } }); return null;
  }
  #continuePath(state, unit, rows) {
    while (unit.order?.type === 'path' && unit.order.path.length && unit.movementLeft > 0) {
      const order = unit.order; const next = order.path[0];
      const enemy = state.units.find(candidate => candidate.transportedByUnitId === null && candidate.ownerId !== unit.ownerId && candidate.x === next.x && candidate.y === next.y);
      const before = { x: unit.x, y: unit.y };
      const result = enemy
        ? (visibleTileIds(state, unit.ownerId).has(next.y * state.world.width + next.x) ? 'ILLEGAL_TARGET' : 'NOT_VISIBLE')
        : this.#move(state, { type: 'unit.move', civId: unit.ownerId, unitId: unit.id, to: next, fromPath: true }, rows);
      if (result || sameTile(unit, before)) {
        if (result === 'INSUFFICIENT_MOVEMENT') return null;
        unit.order = null;
        rows.push({ type: 'unit.pathStopped', civId: unit.ownerId, entityId: unit.id, data: { reason: result || 'ILLEGAL_TARGET' } });
        return result || 'ILLEGAL_TARGET';
      }
      unit.order = order; order.path.shift(); if (!order.path.length) unit.order = null;
    }
    return null;
  }
  #apply(state, command, rows) { switch (command.type) {
    case 'unit.move': return this.#move(state, command, rows);
    case 'unit.path': { const [unit, reason] = this.#owned(state, command, 'unitId', 'units'); if (reason || !Array.isArray(command.path) || !command.path.length) return reason || 'INVALID_COMMAND'; let cursor = { x: unit.x, y: unit.y }; for (const point of command.path) { const destination = normalizedPoint(state.world, point); if (!destination || chebyshevWrapped(state.world, cursor, destination) !== 1) return 'INVALID_COMMAND'; cursor = destination; } unit.order = { type: 'path', path: command.path.map((point) => normalizedPoint(state.world, point)), improvementId: null, progress: 0 }; const start = { x: unit.x, y: unit.y }; const stopped = this.#continuePath(state, unit, rows); if (stopped && sameTile(start, unit)) return stopped; if (command.continue === false) unit.order = null; rows.push({ type: 'unit.pathSet', civId: command.civId, entityId: unit.id, data: { remaining: unit.order?.path.length || 0 } }); return null; }
    case 'unit.attack': { const [unit, reason] = this.#owned(state, command, 'unitId', 'units'); const target = idOf(state.units, command.targetUnitId); if (reason) return reason; if (!target) return 'NOT_FOUND'; if (chebyshevWrapped(state.world, unit, target) !== 1 || isCivilian(this.catalog, unit) || isCivilian(this.catalog, target) || !canFight(state, unit, target)) return 'ILLEGAL_TARGET'; return this.#move(state, { ...command, type: 'unit.move', to: { x: target.x, y: target.y } }, rows); }
    case 'unit.wait': case 'unit.fortify': case 'unit.sleep': case 'unit.wake': { const [unit, reason] = this.#owned(state, command, 'unitId', 'units'); if (reason) return reason; unit.stance = command.type === 'unit.wait' ? 'waiting' : command.type === 'unit.fortify' ? 'fortified' : command.type === 'unit.sleep' ? 'sleeping' : 'active'; unit.order = null; rows.push({ type: command.type, civId: command.civId, entityId: unit.id, data: {} }); return null; }
    case 'unit.foundCity': { const [unit, reason] = this.#owned(state, command, 'unitId', 'units'); const tile = unit && getTile(state.world, unit.x, unit.y); if (reason) return reason; if (unit.typeId !== 'settler' || unit.transportedByUnitId || unit.movementLeft <= 0 || !tile || this.catalog.TERRAIN[tile.terrainId].water || tile.terrainId === 'mountain' || !String(command.name || '').trim() || state.cities.some((city) => chebyshevWrapped(state.world, city, unit) < 4)) return 'ILLEGAL_TARGET'; const workerTile = cityRadiusTiles(state.world, unit).find((candidate) => !(candidate.x === unit.x && candidate.y === unit.y)); if (!workerTile) return 'ILLEGAL_TARGET'; state.units.splice(state.units.indexOf(unit), 1); const city = { id: makeId(state, 'city'), ownerId: command.civId, name: String(command.name).trim().slice(0, 40), x: unit.x, y: unit.y, population: 1, foodStock: 0, buildingIds: [], focus: 'balanced', workedTileIds: [workerTile.id], lockedTileIds: [], specialists: { scientist: 0, taxCollector: 0, entertainer: 0 }, productionQueue: [], cultureByCiv: [{ civId: command.civId, amount: 0 }], greatWorkCivIds: [], disorder: false }; state.cities.push(city); assignCitizens(state, this.catalog, city); const civ = idOf(state.civilizations, command.civId); if (!civ.capitalCityId) civ.capitalCityId = city.id; refreshIntelligence(state, command.civId); rows.push({ type: 'city.founded', civId: command.civId, entityId: city.id, data: { name: city.name } }); return null; }
    case 'unit.improve': { const [unit, reason] = this.#owned(state, command, 'unitId', 'units'); const improvement = this.catalog.IMPROVEMENTS?.[command.improvementId]; if (reason) return reason; if (unit.typeId !== 'worker' || unit.transportedByUnitId || unit.movementLeft <= 0 || !improvement || !improvement.terrains.includes(getTile(state.world, unit.x, unit.y).terrainId)) return 'ILLEGAL_TARGET'; if (improvement.requires && !idOf(state.civilizations, command.civId).knownTechIds.includes(improvement.requires)) return 'PREREQUISITE_MISSING'; unit.order = { type: 'improve', path: [], improvementId: command.improvementId, progress: 0 }; unit.movementLeft = 0; unit.stance = 'waiting'; rows.push({ type: 'unit.improving', civId: command.civId, entityId: unit.id, data: { improvementId: command.improvementId } }); return null; }
    case 'unit.board': { const [unit, reason] = this.#owned(state, command, 'unitId', 'units'); const transport = idOf(state.units, command.transportUnitId); if (reason) return reason; if (!transport) return 'NOT_FOUND'; const unitTile = getTile(state.world, unit.x, unit.y); const transportTile = getTile(state.world, transport.x, transport.y); const adjacentCoast = chebyshevWrapped(state.world, unit, transport) <= 1 && !this.catalog.TERRAIN[unitTile.terrainId].water && transportTile.terrainId === 'coast'; if (unit.movementLeft <= 0 || transport.movementLeft <= 0 || transport.ownerId !== command.civId || this.catalog.UNITS[unit.typeId].domain !== 'land' || this.catalog.UNITS[transport.typeId].domain !== 'sea' || this.catalog.UNITS[transport.typeId].capacity <= 0 || !(sameTile(unit, transport) || adjacentCoast) || state.units.filter((candidate) => candidate.transportedByUnitId === transport.id).length >= this.catalog.UNITS[transport.typeId].capacity) return 'ILLEGAL_TARGET'; unit.transportedByUnitId = transport.id; unit.x = transport.x; unit.y = transport.y; unit.movementLeft = 0; transport.movementLeft = 0; rows.push({ type: 'unit.boarded', civId: command.civId, entityId: unit.id, data: { transportUnitId: transport.id } }); return null; }
    case 'unit.unload': { const [unit, reason] = this.#owned(state, command, 'unitId', 'units'); if (reason || !unit.transportedByUnitId) return reason || 'ILLEGAL_TARGET'; const transport = idOf(state.units, unit.transportedByUnitId); const destination = normalizedPoint(state.world, command.to); const enemyMilitary = destination && state.units.some((candidate) => candidate.transportedByUnitId === null && candidate.ownerId !== command.civId && candidate.x === destination.x && candidate.y === destination.y && !isCivilian(this.catalog, candidate)); if (!transport || transport.movementLeft <= 0 || !destination || enemyMilitary || chebyshevWrapped(state.world, transport, destination) !== 1 || !terrainPassable(this.catalog, this.catalog.UNITS[unit.typeId], getTile(state.world, destination.x, destination.y))) return 'ILLEGAL_TARGET'; unit.transportedByUnitId = null; unit.x = destination.x; unit.y = destination.y; unit.movementLeft = 0; transport.movementLeft = 0; rows.push({ type: 'unit.unloaded', civId: command.civId, entityId: unit.id, data: { to: destination } }); return null; }
    case 'city.rename': {
      const [city, reason] = this.#owned(state, command, 'cityId', 'cities');
      if (reason) return reason;
      if (typeof command.name !== 'string') return 'INVALID_COMMAND';
      const name = command.name.trim();
      if (!name || name.length > 40 || Array.from(name).some(char=>char.charCodeAt(0)<32||char.charCodeAt(0)===127)) return 'INVALID_COMMAND';
      city.name = name;
      refreshIntelligence(state, command.civId);
      rows.push({ type: 'city.renamed', civId: command.civId, entityId: city.id, data: { name } });
      return null;
    }
    case 'city.allocate': return this.#allocate(state, command, rows);
    case 'city.setFocus': { const [city, reason] = this.#owned(state, command, 'cityId', 'cities'); if (reason || !['balanced', 'growth', 'production', 'research'].includes(command.focus)) return reason || 'INVALID_COMMAND'; city.focus = command.focus; assignCitizens(state, this.catalog, city); rows.push({ type: 'city.focusChanged', civId: command.civId, entityId: city.id, data: { focus: city.focus } }); return null; }
    case 'city.queue': return this.#queue(state, command, rows);
    case 'civ.setRates': { const rates = command.rates; if (!isRecord(rates) || ![rates.tax, rates.science, rates.luxury].every((value) => Number.isInteger(value) && value >= 0 && value <= 100 && value % 10 === 0) || rates.tax + rates.science + rates.luxury !== 100) return 'INVALID_ALLOCATION'; idOf(state.civilizations, command.civId).rates = clone(rates); rows.push({ type: 'rates.changed', civId: command.civId, data: { rates } }); return null; }
    case 'civ.selectResearch': { const tech = this.catalog.TECHS[command.techId]; const civ = idOf(state.civilizations, command.civId); if (!tech) return 'NOT_FOUND'; if (civ.knownTechIds.includes(command.techId)) return 'ILLEGAL_TARGET'; if (!tech.requires.every((id) => civ.knownTechIds.includes(id))) return 'PREREQUISITE_MISSING'; civ.research.activeTechId = command.techId; rows.push({ type: 'research.selected', civId: command.civId, entityId: command.techId, data: {} }); return null; }
    case 'civ.changeGovernment': { const government = this.catalog.GOVERNMENTS[command.governmentId]; const civ = idOf(state.civilizations, command.civId); if (!government) return 'NOT_FOUND'; if (government.requires && !civ.knownTechIds.includes(government.requires)) return 'PREREQUISITE_MISSING'; if (civ.government.currentId === command.governmentId || civ.government.pendingId) return 'ILLEGAL_TARGET'; civ.government.pendingId = command.governmentId; civ.government.transitionRoundsLeft = 2; rows.push({ type: 'government.transition', civId: command.civId, data: { governmentId: command.governmentId } }); return null; }
    case 'diplomacy.propose': return this.#propose(state, command, rows);
    case 'diplomacy.respond': return this.#respond(state, command, rows);
    case 'diplomacy.declareWar': return this.#war(state, command, rows);
    case 'trade.open': return this.#openTrade(state, command, rows);
    case 'trade.close': { const route = idOf(state.tradeRoutes, command.tradeRouteId); if (!route) return 'NOT_FOUND'; if (route.ownerCivId !== command.civId) return 'NOT_OWNER'; state.tradeRoutes.splice(state.tradeRoutes.indexOf(route), 1); rows.push({ type: 'trade.closed', civId: command.civId, entityId: route.id, data: {} }); return null; }
    case 'space.launch': { const program = state.spacePrograms.find((item) => item.civId === command.civId); if (!idOf(state.civilizations, command.civId).knownTechIds.includes('spaceflight') || program.launchedRound || program.components.structure < 3 || program.components.propulsion < 2 || program.components.support < 1) return 'PREREQUISITE_MISSING'; program.launchedRound = state.turn.round; program.arrivalRound = state.turn.round + scaled(10, state.config.speed); rows.push({ type: 'space.launched', civId: command.civId, data: { arrivalRound: program.arrivalRound } }); return null; }
    case 'civ.endTurn': return this.#endTurn(state, command, rows);
    default: return 'INVALID_COMMAND';
  } }
  #allocate(state, command, rows) { const [city, reason] = this.#owned(state, command, 'cityId', 'cities'); if (reason) return reason; if (!Array.isArray(command.workedTileIds) || !Array.isArray(command.lockedTileIds) || !isRecord(command.specialists)) return 'INVALID_ALLOCATION'; const radius = new Set(cityRadiusTiles(state.world, city).map((tile) => tile.id)); const unique = new Set(command.workedTileIds); const workedElsewhere = new Set(state.cities.filter((candidate) => candidate.ownerId === command.civId && candidate.id !== city.id).flatMap((candidate) => candidate.workedTileIds)); const specialistCount = command.specialists.scientist + command.specialists.taxCollector + command.specialists.entertainer; if (unique.size !== command.workedTileIds.length || !command.workedTileIds.every((id) => radius.has(id) && id !== city.y * state.world.width + city.x && !workedElsewhere.has(id)) || !command.lockedTileIds.every((id) => unique.has(id)) || ![command.specialists.scientist, command.specialists.taxCollector, command.specialists.entertainer].every((value) => Number.isInteger(value) && value >= 0) || command.workedTileIds.length + specialistCount !== city.population) return 'INVALID_ALLOCATION'; city.workedTileIds = [...command.workedTileIds]; city.lockedTileIds = [...command.lockedTileIds]; city.specialists = clone(command.specialists); rows.push({ type: 'city.allocated', civId: command.civId, entityId: city.id, data: {} }); return null; }
  #queue(state, command, rows) { const [city, reason] = this.#owned(state, command, 'cityId', 'cities'); if (reason) return reason; const queue = city.productionQueue; if (command.action === 'append') { const item = command.item; if (!isRecord(item) || !['unit', 'building', 'project'].includes(item.kind) || (item.kind === 'unit' ? !this.catalog.UNITS[item.definitionId] : item.kind === 'building' ? !this.catalog.BUILDINGS[item.definitionId] : !this.catalog.PROJECTS[item.definitionId])) return 'INVALID_COMMAND'; const definition = item.kind === 'unit' ? this.catalog.UNITS[item.definitionId] : item.kind === 'building' ? this.catalog.BUILDINGS[item.definitionId] : this.catalog.PROJECTS[item.definitionId]; if (queue.length >= 5) return 'QUEUE_FULL'; const requires = definition.requires; if (requires && !idOf(state.civilizations, command.civId).knownTechIds.includes(requires)) return 'PREREQUISITE_MISSING'; if (item.kind === 'building' && city.buildingIds.includes(item.definitionId)) return 'ILLEGAL_TARGET'; queue.push({ id: makeId(state, 'queue'), kind: item.kind, definitionId: item.definitionId, progress: 0, repeat: Boolean(item.repeat) }); } else { const index = queue.findIndex((item) => item.id === command.itemId); if (index < 0) return 'NOT_FOUND'; if (command.action === 'remove') queue.splice(index, 1); else if (command.action === 'setRepeat') queue[index].repeat = Boolean(command.repeat); else if (command.action === 'move' && Number.isInteger(command.toIndex) && command.toIndex >= 0 && command.toIndex < queue.length) queue.splice(command.toIndex, 0, queue.splice(index, 1)[0]); else return 'INVALID_COMMAND'; } rows.push({ type: 'city.queueChanged', civId: command.civId, entityId: city.id, data: { action: command.action } }); return null; }
  #propose(state, command, rows) { const target = idOf(state.civilizations, command.targetCivId); const relation = relationFor(state, command.civId, command.targetCivId); const source = idOf(state.civilizations, command.civId); if (!target) return 'NOT_FOUND'; if (!relation?.contacted) return 'DIPLOMACY_REQUIRED'; if (!['peace', 'openBorders', 'tradeAgreement', 'alliance', 'exchange'].includes(command.kind) || !isRecord(command.terms)) return 'INVALID_COMMAND'; const { goldFromA = 0, goldFromB = 0, techIdsFromA = [], techIdsFromB = [] } = command.terms; const allTechIds = [...techIdsFromA, ...techIdsFromB]; if (![goldFromA, goldFromB].every((value) => Number.isInteger(value) && value >= 0) || !Array.isArray(techIdsFromA) || !Array.isArray(techIdsFromB) || new Set(allTechIds).size !== allTechIds.length || !techIdsFromA.every((id) => source.knownTechIds.includes(id)) || !techIdsFromB.every((id) => target.knownTechIds.includes(id)) || command.expiresRound !== undefined && (!Number.isInteger(command.expiresRound) || command.expiresRound < state.turn.round)) return 'INVALID_COMMAND'; const treaty = { id: makeId(state, 'treaty'), civAId: command.civId, civBId: target.id, kind: command.kind, status: 'proposed', proposedByCivId: command.civId, terms: { goldFromA, goldFromB, techIdsFromA: [...techIdsFromA], techIdsFromB: [...techIdsFromB] }, expiresRound: command.expiresRound ?? null }; state.treaties.push(treaty); adjustRelation(state, command.civId, target.id, 1); rows.push({ type: 'treaty.proposed', civId: command.civId, entityId: treaty.id, data: { targetCivId: target.id, kind: treaty.kind } }); return null; }
  #respond(state, command, rows) { const treaty = idOf(state.treaties, command.treatyId); if (!treaty) return 'NOT_FOUND'; if (treaty.status !== 'proposed' || treaty.proposedByCivId === command.civId || treaty.civAId !== command.civId && treaty.civBId !== command.civId) return 'ILLEGAL_TARGET'; treaty.status = command.accept ? 'active' : 'rejected'; if (command.accept) { const a = idOf(state.civilizations, treaty.civAId); const b = idOf(state.civilizations, treaty.civBId); if (a.treasury < treaty.terms.goldFromA || b.treasury < treaty.terms.goldFromB) return 'ILLEGAL_TARGET'; a.treasury -= treaty.terms.goldFromA; b.treasury += treaty.terms.goldFromA; b.treasury -= treaty.terms.goldFromB; a.treasury += treaty.terms.goldFromB; treaty.terms.techIdsFromA.filter((id) => a.knownTechIds.includes(id)).forEach((id) => { if (!b.knownTechIds.includes(id)) b.knownTechIds.push(id); }); treaty.terms.techIdsFromB.filter((id) => b.knownTechIds.includes(id)).forEach((id) => { if (!a.knownTechIds.includes(id)) a.knownTechIds.push(id); }); [a, b].forEach((civ) => { if (civ.research.activeTechId && civ.knownTechIds.includes(civ.research.activeTechId)) civ.research.activeTechId = null; }); if (treaty.kind === 'peace') { const relation = relationFor(state, a.id, b.id); if (relation) relation.atWar = false; } adjustRelation(state, a.id, b.id, 10); } else adjustRelation(state, treaty.civAId, treaty.civBId, -5); rows.push({ type: command.accept ? 'treaty.accepted' : 'treaty.rejected', civId: command.civId, entityId: treaty.id, data: {} }); return null; }
  #war(state, command, rows) { const target = idOf(state.civilizations, command.targetCivId); if (!target || target.id === command.civId) return target ? 'ILLEGAL_TARGET' : 'NOT_FOUND'; const relation = relationFor(state, command.civId, target.id); if (!relation?.contacted) return 'DIPLOMACY_REQUIRED'; relation.atWar = true; adjustRelation(state, command.civId, target.id, -30); state.treaties.filter((treaty) => treaty.status === 'active' && (treaty.civAId === command.civId && treaty.civBId === target.id || treaty.civBId === command.civId && treaty.civAId === target.id)).forEach((treaty) => { treaty.status = 'expired'; }); rows.push({ type: 'war.declared', civId: command.civId, entityId: target.id, data: {} }); return null; }
  #routeBetween(state, origin, destination) { const originId = origin.y * state.world.width + origin.x; const destinationId = destination.y * state.world.width + destination.x; const hasHarbor = (city) => city.buildingIds.includes('harbor'); const seaAllowed = hasHarbor(origin) && hasHarbor(destination); const queue = [{ x: origin.x, y: origin.y, path: [originId] }]; const visited = new Set([originId]); while (queue.length) { const current = queue.shift(); if (current.x === destination.x && current.y === destination.y) return current.path; for (const tile of adjacent(state.world, current)) { if (visited.has(tile.id)) continue; const isEndpoint = tile.id === destinationId || tile.id === originId; const legal = isEndpoint || tile.routeId !== null || (seaAllowed && this.catalog.TERRAIN[tile.terrainId].water); if (!legal) continue; visited.add(tile.id); queue.push({ x: tile.x, y: tile.y, path: [...current.path, tile.id] }); } } return null; }
  #refreshTradeRoutes(state) { state.tradeRoutes.forEach((route) => { const origin = idOf(state.cities, route.originCityId); const destination = idOf(state.cities, route.destinationCityId); if (!origin || !destination || origin.ownerId !== route.ownerCivId) { route.status = 'suspended'; route.suspendedReason = 'CITY_LOST'; return; } if (origin.ownerId !== destination.ownerId && isAtWar(state, origin.ownerId, destination.ownerId)) { route.status = 'suspended'; route.suspendedReason = 'WAR'; return; } if (origin.ownerId !== destination.ownerId && !this.#hasActiveTreaty(state, origin.ownerId, destination.ownerId, ['tradeAgreement', 'alliance'])) { route.status = 'suspended'; route.suspendedReason = 'AGREEMENT_EXPIRED'; return; } const path = this.#routeBetween(state, origin, destination); route.status = path ? 'active' : 'suspended'; route.suspendedReason = path ? null : 'CONNECTION_BROKEN'; if (path) route.pathTileIds = path; }); }
  #openTrade(state, command, rows) { const [origin, reason] = this.#owned(state, command, 'originCityId', 'cities'); const destination = idOf(state.cities, command.destinationCityId); if (reason) return reason; if (!destination || destination.id === origin.id) return destination ? 'ILLEGAL_TARGET' : 'NOT_FOUND'; if (destination.ownerId !== command.civId) { const relation = relationFor(state, command.civId, destination.ownerId); const agreement = state.treaties.some((treaty) => treaty.status === 'active' && ['tradeAgreement', 'alliance'].includes(treaty.kind) && (treaty.civAId === command.civId && treaty.civBId === destination.ownerId || treaty.civBId === command.civId && treaty.civAId === destination.ownerId)); if (!relation?.contacted || !agreement) return 'DIPLOMACY_REQUIRED'; } if ([origin.id, destination.id].some(id => state.tradeRoutes.filter(route => route.status === 'active' && [route.originCityId, route.destinationCityId].includes(id)).length >= 3) || state.tradeRoutes.some(route => [route.originCityId, route.destinationCityId].includes(origin.id) && [route.originCityId, route.destinationCityId].includes(destination.id))) return 'ILLEGAL_TARGET'; const pathTileIds = this.#routeBetween(state, origin, destination); if (!pathTileIds) return 'ILLEGAL_TARGET'; const route = { id: makeId(state, 'route'), ownerCivId: command.civId, originCityId: origin.id, destinationCityId: destination.id, pathTileIds, status: 'active', suspendedReason: null }; state.tradeRoutes.push(route); rows.push({ type: 'trade.opened', civId: command.civId, entityId: route.id, data: { status: route.status } }); return null; }
  #endTurn(state, command, rows) { const civId = command.civId; for (const unit of state.units.filter((unit) => unit.ownerId === civId)) { if (unit.order?.type === 'improve') { const improvement = this.catalog.IMPROVEMENTS?.[unit.order.improvementId]; unit.order.progress += 1; if (improvement && unit.order.progress >= scaled(improvement.cost, state.config.speed)) { const improvementId = unit.order.improvementId; const tile = getTile(state.world, unit.x, unit.y); tile[improvement.kind === 'route' ? 'routeId' : 'landUseId'] = improvementId; unit.order = null; rows.push({ type: 'improvement.completed', civId, entityId: unit.id, data: { improvementId } }); } } }
    state.treaties.filter((treaty) => ['active', 'proposed'].includes(treaty.status) && treaty.expiresRound !== null && treaty.expiresRound <= state.turn.round).forEach((treaty) => { treaty.status = 'expired'; rows.push({ type: 'treaty.expired', civId: null, entityId: treaty.id, data: {} }); });
    this.#refreshTradeRoutes(state);
    if (!idOf(state.civilizations, civId).eliminated) settleCivilization(state, this.catalog, civId, rows);
    const endedRound = state.turn.round;
    for (const row of rows) row.round ??= endedRound;
    const nextIndex = (state.turn.activeCivIndex + 1) % state.civilizations.length;
    state.turn.activeCivIndex = nextIndex; state.turn.activeCivId = state.civilizations[nextIndex].id;
    if (nextIndex === 0) {
      this.#checkElimination(state, rows); this.#checkVictory(state, rows);
      for (const row of rows) row.round ??= endedRound;
      if (state.turn.status === 'running') state.turn.round += 1;
    }
    if (state.turn.status === 'running') {
      state.units.filter(unit => unit.ownerId === state.turn.activeCivId).forEach(unit => {
        unit.movementLeft = this.catalog.UNITS[unit.typeId].movement;
        if (unit.stance === 'waiting') unit.stance = 'active';
      });
      refreshIntelligence(state, state.turn.activeCivId);
      state.units.filter(unit => unit.ownerId === state.turn.activeCivId && unit.order?.type === 'path').forEach(unit => this.#continuePath(state, unit, rows));
    }
    rows.push({ type: 'turn.ended', round: endedRound, civId, data: { nextCivId: state.turn.activeCivId } }); return null;
  }

  #checkElimination(state, rows) { for (const civ of state.civilizations) if (!civ.eliminated && !state.cities.some((city) => city.ownerId === civ.id) && !state.units.some((unit) => unit.ownerId === civ.id && unit.typeId === 'settler')) { civ.eliminated = true; const remainingUnitIds = state.units.filter((unit) => unit.ownerId === civ.id).map((unit) => unit.id); state.units = state.units.filter((unit) => unit.ownerId !== civ.id); rows.push({ type: 'civ.eliminated', civId: civ.id, data: { removedUnitIds: remainingUnitIds } }); } }
  #checkVictory(state, rows) { const score = (civ) => { const program = state.spacePrograms.find((item) => item.civId === civ.id); return state.cities.filter((city) => city.ownerId === civ.id).reduce((total, city) => total + city.population * 10 + city.buildingIds.length * 8 + (city.cultureByCiv.find((row) => row.civId === civ.id)?.amount || 0), civ.knownTechIds.length * 25 + (program.components.structure + program.components.propulsion + program.components.support) * 20); }; const qualified = new Map(); const add = (civ, type) => qualified.set(civ.id, { civ, type }); const living = state.civilizations.filter((civ) => !civ.eliminated); if (living.length === 1) add(living[0], 'conquest'); state.spacePrograms.filter((program) => program.arrivalRound !== null && program.arrivalRound <= state.turn.round).forEach((program) => add(idOf(state.civilizations, program.civId), 'space')); const threshold = scaled(3000, state.config.speed); state.civilizations.filter((civ) => state.cities.filter((city) => city.ownerId === civ.id && city.greatWorkCivIds.includes(civ.id) && (city.cultureByCiv.find((row) => row.civId === civ.id)?.amount || 0) >= threshold).length >= 3).forEach((civ) => add(civ, 'culture')); if (!qualified.size && state.turn.round >= state.config.maxRounds) state.civilizations.forEach((civ) => add(civ, 'score')); if (!qualified.size) return; const entries = [...qualified.values()]; const highScore = Math.max(...entries.map(({ civ }) => score(civ))); const winners = entries.filter(({ civ }) => score(civ) === highScore); state.turn.status = 'finished'; state.turn.victoryType = winners[0].type; state.turn.winnerCivIds = winners.map(({ civ }) => civ.id); rows.push({ type: 'game.finished', civId: null, data: { victoryType: state.turn.victoryType, winnerCivIds: state.turn.winnerCivIds, scores: winners.map(({ civ }) => ({ civId: civ.id, score: score(civ) })) } }); }
}
